--- 
title: "Справочник РТП"
author: "О.С. Малютин"
date: "`r format(Sys.time(), '%d %B, %Y')`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
description: "Справочник руководителя тушения пожара"
output:
  bookdown::html_book:
    theme: default
---

```{r setup, echo=FALSE}

library(kableExtra)
library(magrittr)
```


# Введение {-}

Данная книга появилась как попытка переосмыслить подход к составлению справочников руководителя тушения пожара с точки зрения применения современных технологий.

> Книга создана в [ФБГОУ ВО Сибирская пожарно-спасательная академия ГПС МЧС России](http://sibpsa.ru/)

В ее основу был положен полюбившийся многим, до сих пор по праву считающийся лучшим справочником РТП - **Справочник руководителя тушения пожара (РТП). Иванников В.П., Клюс П.П., Москва, 1987г.** [@RTP1987]

На этом справочнике выросло не одно поколение пожарных России и стран СНГ.

Вместе с тем очевидно, что книга написанная много десятилетий назад в стране которой больше не существует и в условиях совершенно иной пожарной опасности веществ и материалов, технически все же во многом устарела. Появились новые способы тушения пожаров, изменились подходы к проведению пожарно-тактических расчетов, появилась новая техника, изменилась нормативная база и руководящие документы.

Много лет мы задавали себе вопрос - почему нельзя взять старый, проверенный временем справочник и просто актуализировать содержащуюся в нем информацию? Очевидно, что это большой объем работы, а времени зачастую не хватает даже для выполнения текущих заданий. И мы все врем откладывали, надеясь, что кто-то возьмет этот труд на себя.

Но вот веяния нового времени коснулись и пожарной охраны. С появлением развитых онлайн сервисов для организации совместной работы мы получили возможность привлечь к работе над одной книгой большое количество людей. И потому мы возвращаемся к задаче создания обновленного справочника руководителя тушения пожара. Справочника который объединил бы в себе все лучшее из старых проверенных временем документов и новые знания в области пожаротушения. Справочника который стал бы по настоящему популярным и востребованным в сообществе пожарных России. Справочника который был бы легко модифицируем под так быстро меняющиеся в наше время реалии.

